name: CI
on: [push, pull_request]
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
    actions: write
    contents: read
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: julia-actions/setup-julia@v2
            - uses: julia-actions/cache@v2
            - name: 'Check formatting'
              run: |
                julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
                julia -e 'using JuliaFormatter; exit(!format(".", overwrite=false))'
              shell: bash
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: julia-actions/setup-julia@v2
            - uses: julia-actions/cache@v2
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
